### ISSUE TITLE
import-module DLConversionV2 from C: drive in start-MultipleDistributionListMigration.ps1

### ISSUE THREAD

**Issue by TPok1707** [timmcmic/DLConversionV2#107]
Some commits ago the line

`Start-Job -Name $jobName -InitializationScript {import-module DLConversionV2} -ScriptBlock ...`

was changed to

`Start-Job -Name $jobName -InitializationScript {import-module c:\repository\dlconversionv2\dlconversionv2.psd1 -force} -ScriptBlock...`

in start-MultipleDistributionListMigration.ps1 twice.

This leads to a crash during migration because the module cannot be found there.

**Comment by timmcmic** [comment]
Thanks - I accidentally submitted my test code.  Let me fix it and republish asap.


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________
From: TPok1707 ***@***.***>
Sent: Thursday, February 2, 2023 11:44 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] import-module DLConversionV2 from C: drive in start-MultipleDistributionListMigration.ps1 (Issue #107)


Some commits ago the line

Start-Job -Name $jobName -InitializationScript {import-module DLConversionV2} -ScriptBlock ...

was changed to

Start-Job -Name $jobName -InitializationScript {import-module c:\repository\dlconversionv2\dlconversionv2.psd1 -force} -ScriptBlock...

in start-MultipleDistributionListMigration.ps1 twice.

This leads to a crash during migration because the module cannot be found there.

**Comment by TPok1707** [comment]
Fine. I fixed it locally for me currently.

Thank you for your great work. I don't know how would have ever done my current task without your migration scripts.

**Comment by timmcmic** [comment]
Fixed 2.9.6.3
