### ISSUE TITLE
The term 'get-o365Recipient' is not recognized

### ISSUE THREAD

**Issue by jspern** [timmcmic/DLConversionV2#120]
When running a basic migration, it errors out due to the renamed cmdlets not being found.

```
Get-O365DLConfiguration : The term 'get-o365Recipient' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.9.6.4\DLConversionV2.psm1:1430 char:39
+ ... nfiguration=Get-O365DLConfiguration -groupSMTPAddress $groupSMTPAddre ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-o365Recipient:String) [Get-o365DLConfiguration], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Get-o365DLConfiguration
```

**Comment by timmcmic** [comment]
Are you running this from a standard powershell and not an exchange management shell.

Can you send me a full log?

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: jspern ***@***.***>
Sent: Monday, February 13, 2023 12:19 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] The term 'get-o365Recipient' is not recognized (Issue #120)


When running a basic migration, it errors out due to the renamed cmdlets not being found.

Get-O365DLConfiguration : The term 'get-o365Recipient' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or

if a path was included, verify that the path is correct and try again.

At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.9.6.4\DLConversionV2.psm1:1430 char:39

+ ... nfiguration=Get-O365DLConfiguration -groupSMTPAddress $groupSMTPAddre ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (get-o365Recipient:String) [Get-o365DLConfiguration], CommandNotFoundException

    + FullyQualifiedErrorId : CommandNotFoundException,Get-o365DLConfiguration

-

**Comment by jspern** [comment]
I was able to narrow it down to .NET 4.8 not being installed on the machine I was running the migration from. All is good now, thank you.

**Comment by timmcmic** [comment]
I'd still like to see the log - you should have been failing before this I would have thought.

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by jspern** [comment]
I can't share the full logs as they contain sensitive information that I'm not authorized to share; I would have to sanitize the log first. The other thing I did change to get it working was to specify the `-exchangeOnlineCredential` parameter, which I was not doing previously because the documentation said that it was an optional parameter. I was able to successfully migrate one DL, but now on another I am getting an "OFFICE_365_DEPENDENCY_NOT_FOUND_EXCEPTION" for one particular member of the DL.
