### ISSUE TITLE
Infinite loop if DL name is the same as its primary email address

### ISSUE THREAD

**Issue by jspern** [timmcmic/DLConversionV2#121]
If migrating a DL that is named the same as its primary email address, the module will eventually enter an infinite loop where it states "Group found in O365 - wait 30 seconds - try again"

**Comment by timmcmic** [comment]
Do you by chance have a log file that I could look at.  You can send it to dlconversionv2 at service dot microsoft dot com

All of my test DLs have the same name as the primary SMTP address prefix and do not have the same issue so I'd like to see what attributes you have for comparison.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: jspern ***@***.***>
Sent: Tuesday, February 14, 2023 9:37 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Infinite loop if DL name is the same as its primary email address (Issue #121)


If migrating a DL that is named the same as its primary email address, the module will eventually enter an infinite loop where it states "Group found in O365 - wait 30 seconds - try again"

-

**Comment by jspern** [comment]
I will see if I can sanitize one of the log files and send it over. Just to clarify, the lists I was having the issue with had the full primary email address as their names -- e.g., both the name and primary SMTP address of an affected list would be list@domain.com

**Comment by timmcmic** [comment]
Thanks - that's certainly odd to say the least.  Usually when it loops around in the get group prior to deletion its due to the group not being moved to an OU that does not sync or AD Connect not submitting the deletion to azure.  There's also always the potential for forward sync delays.

In my lab the raw ldap attributes are:

Name:  atestgroup183
Mail:  ***@***.******@***.***>
ProxyAddresses: ***@***.******@***.***>
Pre-Windows2000Name:  atestgroup-adfdfasdfadsf

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by timmcmic** [comment]
If you want to reach out to me on teams I'd be more than happy to review the logs with you in teams...

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================
