### ISSUE TITLE
Error in Determine if the calcualted routing address is already in use.

### ISSUE THREAD

**Issue by githubths** [timmcmic/DLConversionV2#129]
Script set-Office365DLMV.ps1

[3/28/2023 1:55:05 PM] - Determine if the calcualted routing address is already in use.
Write-ErrorMessage : Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation
couldn't be performed because object 'TestDL9890@test.mail.onmicrosoft.com' couldn't be found on
'DB6PR06A001DC06.EURPR06A001.prod.outlook.com'.
At C:\Users\Test\AppData\Local\Temp\2\tmpEXO_jzwkrfob.men\tmpEXO_jzwkrfob.men.psm1:1121 char:13
+             Write-ErrorMessage $ErrorObject
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Recipient], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : [Server=AM6PR06MB5795,RequestId=7f6f2d5f-726b-5584-2121-922596043d50,TimeStamp=Tue, 28 M
   ar 2023 13:55:04 GMT],Write-ErrorMessage

Please Replace 
Line : 333
if (get-o365Recipient -identity $hybridRemoteRoutingAddress)
with
if (get-o365Recipient -identity $hybridRemoteRoutingAddress -ErrorAction SilentlyContinue)

**Comment by timmcmic** [comment]
Why am I doing that in this instance?

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: Stefan Thoma ***@***.***>
Sent: Tuesday, March 28, 2023 11:15 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Error in Determine if the calcualted routing address is already in use. (Issue #129)


Script set-Office365DLMV.ps1

[3/28/2023 1:55:05 PM] - Determine if the calcualted routing address is already in use.
Write-ErrorMessage : Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation
couldn't be performed because object ***@***.******@***.***>' couldn't be found on
'DB6PR06A001DC06.EURPR06A001.prod.outlook.com'.
At C:\Users\Test\AppData\Local\Temp\2\tmpEXO_jzwkrfob.men\tmpEXO_jzwkrfob.men.psm1:1121 char:13

*                Write-ErrorMessage $ErrorObject

  *

*                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*

     *   CategoryInfo : NotSpecified: (:) [Get-Recipient], ManagementObjectNotFoundException
     *   FullyQualifiedErrorId : [Server=AM6PR06MB5795,RequestId=7f6f2d5f-726b-5584-2121-922596043d50,TimeStamp=Tue, 28 M
ar 2023 13:55:04 GMT],Write-ErrorMessage

Please Replace
Line : 333
if (get-o365Recipient -identity $hybridRemoteRoutingAddress)
with
if (get-o365Recipient -identity $hybridRemoteRoutingAddress -ErrorAction SilentlyContinue)

-
