### ISSUE TITLE
import-module DLConversionV2 failed to loaded when start-MultipleDistributionListMigration.ps1

### ISSUE THREAD

**Issue by ixUpRiSinGxi** [timmcmic/DLConversionV2#134]
Using the latest version of DLConversionV2 (2.9.8), and now receiving this error in testing multi-DL moves below that the module could not be loaded since this folder directory does not exist.

import-module : The specified module 'c:\repository\dlconversionv2\dlconversionv2.psd1' was not loaded because no
valid module file was found in any module directory.
At line:1 char:1
+ import-module c:\repository\dlconversionv2\dlconversionv2.psd1 -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (c:\repository\d...nversionv2.psd1:String) [Import-Module], FileNot
   FoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Want to say awesome work! This script has been super helpful in testing a path to migrate DLs.

**Comment by timmcmic** [comment]
Fixed 2.9.8.1 - my apologies to the group I failed to revert the debug statement I was using for testing again.

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: ixUpRiSinGxi ***@***.***>
Sent: Friday, April 14, 2023 12:25 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] import-module DLConversionV2 failed to loaded when start-MultipleDistributionListMigration.ps1 (Issue #134)


Using the latest version of DLConversionV2 (2.9.8), and now receiving this error in testing multi-DL moves below that the module could not be loaded since this folder directory does not exist.

import-module : The specified module 'c:\repository\dlconversionv2\dlconversionv2.psd1' was not loaded because no
valid module file was found in any module directory.
At line:1 char:1

  *   import-module c:\repository\dlconversionv2\dlconversionv2.psd1 -force

*          + CategoryInfo          : ResourceUnavailable: (c:\repository\d...nversionv2.psd1:String) [Import-Module], FileNot

*         FoundException

*          + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

*

*

  *

Have to say awesome work! This has been super helpful.

-

**Comment by ixUpRiSinGxi** [comment]
Looks like it is fixed now, thanks again.
