### ISSUE TITLE
Get-NormalizedDN : Cannot bind argument to parameter 'DN' because it is an empty string.

### ISSUE THREAD

**Issue by TSideScripting** [timmcmic/DLConversionV2#147]
Hi there,
We've been using this module a lot and so far have had a lot of positive results.
Unfortunately there are a few groups that fail to migrate with this error appearing near the end of the log:
```
[28/07/2023 18:28:42] - We have send as names that require distinguished names.
[28/07/2023 18:28:42] - Processing identity = Authenticated Users
[28/07/2023 18:28:42] - Testing for NTAuthority\Self
[28/07/2023 18:28:42] - There are DNs to be normalized.
[28/07/2023 18:28:42] - Processing DN = 
[28/07/2023 18:28:42] - Unable to normalize the DN to an object with SMTP.
Get-NormalizedDN : Cannot bind argument to parameter 'DN' because it is an empty string.
At C:\Program 
Files\WindowsPowerShell\Modules\DLConversionV2\2.9.8.13\Get-GroupSendAsPermission.ps1:283 char:100
+ ...  -globalCatalogServer $globalCatalogServer -DN $dnToNormalize -adCred ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-NormalizedDN], ParameterBindingValidationExcep 
   tion
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-Normalized 
   DN
```
Up to that point and before I can see the script being able to find the DN of the mail-enabled group.
Let me know if you need the full log file and where to send it to.

**Comment by TSideScripting** [comment]
I just updated the module to the latest version (2.9.8.15) and still experiencing the same issue.

**Comment by timmcmic** [comment]
Dlconversionv2 at support dot Microsoft dot com


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________
From: TSide ***@***.***>
Sent: Friday, July 28, 2023 1:46 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Get-NormalizedDN : Cannot bind argument to parameter 'DN' because it is an empty string. (Issue #147)


Hi there,
We've been using this module a lot and so far have had a lot of positive results.
Unfortunately there are a few groups that fail to migrate with this error appearing near the end of the log:

[28/07/2023 18:28:42] - We have send as names that require distinguished names.
[28/07/2023 18:28:42] - Processing identity = Authenticated Users
[28/07/2023 18:28:42] - Testing for NTAuthority\Self
[28/07/2023 18:28:42] - There are DNs to be normalized.
[28/07/2023 18:28:42] - Processing DN =
[28/07/2023 18:28:42] - Unable to normalize the DN to an object with SMTP.
Get-NormalizedDN : Cannot bind argument to parameter 'DN' because it is an empty string.
At C:\Program
Files\WindowsPowerShell\Modules\DLConversionV2\2.9.8.13\Get-GroupSendAsPermission.ps1:283 char:100
+ ...  -globalCatalogServer $globalCatalogServer -DN $dnToNormalize -adCred ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-NormalizedDN], ParameterBindingValidationExcep
   tion
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-Normalized
   DN


Up to that point and before I can see the script being able to find the DN of the mail-enabled group.
Let me know if you need the full log file and where to send it to.

**Comment by TSideScripting** [comment]
Hi, I have tried to send the log twice from 2 different emails but your mail system is refusing connection from mine (it's an outlook dot com email address...)

**Comment by timmcmic** [comment]
Let's make sure I sent you the right address.

DLConversionV2 at service dot microsoft dot com

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by timmcmic** [comment]
After reviewing the log files I determined that we were failing when reviewing the send as permissions on the object.

In this case BUILTIN security principals other than SELF were assigned send as rights.  BUILTIN principals do not resolve to an object with a DN causing this to fail.

.17 was released that covers this.  Now if anything builtin that is not self is located it is skipped.
