### ISSUE TITLE
Issue with multi-distribution list migration

### ISSUE THREAD

**Issue by jakke91** [timmcmic/DLConversionV2#148]
Hello,

 I'm doing something wrong here, but I do not know what.  Help would be appreciated.

![DLConversion](https://github.com/timmcmic/DLConversionV2/assets/140384079/812c6d6e-9f99-4524-a30b-094e6ff79a71)

**Comment by timmcmic** [comment]
You are using the start-distributionlistmigration command instead of the start-multipleDistributionlistMigration command.  Multiple will accept an array of SMTP addresses.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: jakke91 ***@***.***>
Sent: Tuesday, August 1, 2023 9:31 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Issue with multi-distribution list migration (Issue #148)


Hello,

I'm doing something wrong here, but I do not know what. Help would be appreciated.

[DLConversion]<https://user-images.githubusercontent.com/140384079/257529089-812c6d6e-9f99-4524-a30b-094e6ff79a71.png>

-

**Comment by jakke91** [comment]
stupid me (again).

cheers Mr. Tim.
