### ISSUE TITLE
Add interactive login to Exchange Online connection

### ISSUE THREAD

**Issue by mardahl** [timmcmic/DLConversionV2#151]
Hi McMichael!

I have an issue with a tenant where I can't get a cert/appreg and basic auth is disabled.
So Interactive sign-in works well for the new EXOV3 module. Could you add that in?
I don't have a clear enough picture to do a PR :(

Thanks for all you do!

**Comment by timmcmic** [comment]
If you do not specify any credentials it performs interactive auth today.

From: Michael Mardahl ***@***.***>
Sent: Thursday, November 9, 2023 1:36 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Add interactive login to Exchange Online connection (Issue #151)


Hi McMichael!

I have an issue with a tenant where I can't get a cert/appreg and basic auth is disabled.
So Interactive sign-in works well for the new EXOV3 module. Could you add that in?
I don't have a clear enough picture to do a PR :(

Thanks for all you do!

-

**Comment by mardahl** [comment]
Thanks for clearing that up. I was trying to gather what was needed by looking at the module code, and it looked like a credential option was required.
I see now that it works in interactive mode :)

**Comment by timmcmic** [comment]
When I moved to graph since the options were cert or interactive I implemented interactive for both cloud connections.  Now you’ll be prompted more than once potentially - but one is usually as simple as keeping the account logged in.

Tim


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________
