### ISSUE TITLE
Conversion fails if there is not an explicit send-as user in AD

### ISSUE THREAD

**Issue by dickfrazier** [timmcmic/DLConversionV2#16]
I have run into quite a few groups in our system that have a no-longer-existing account with send-as permissions, and no valid accounts with send-as permissions in the ACL. However, when I pull the DL up in the cloud it shows valid owners who would obviously have the send-as permission.  To make it work I have to pull up the ACL and add a current user with explicit send-as permissions and re-sync.  Expected behavior? Not sure if there is a workaround

[9/24/2021 11:50:08 AM] - ********************************************************************************
[9/24/2021 11:50:11 AM] - Unablet to retrive the object by name.
get-adobject : Variable: 'sendAsName' found in expression: $sendAsName is not defined.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.3.97.25\Get-GroupSendAsPermission.ps1:177 char:50
+ ... AsRightDN+=(get-adobject -filter {SAMAccountName -eq $sendAsName} -se ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ADObject], ArgumentException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Comm 
   ands.GetADObject

![image](https://user-images.githubusercontent.com/89863919/134720810-b7d8c1fa-34e2-46e5-9380-cdacfab68d4f.png)

![image](https://user-images.githubusercontent.com/89863919/134720760-8ad5f9ee-61bd-4baa-b741-8f5411ee5700.png)

**Comment by dickfrazier** [comment]
In testing I first removed just the invalid accounts from the ACL and synced hoping that them being gone would resolve the issue but still had an issue unless I gave a valid account explicit send-as permission in the ACL

**Comment by timmcmic** [comment]
Please send me the full log timmcmic at microsoft dot com.

Send as permissions aren't replicated through ad connect - so this should be pulling anything that has local send as rights on the object.

**Comment by timmcmic** [comment]
Ok - so this appears to be an orphaned send as permission.

When the get send as rights on the group is called - the typical return is the extended right that has an identity reference.  The identity reference is generally in the format of DOMAIN\SAMACCOUNTNAME.  When you assign the send as right to an account - and then subsequently delete that account from active directory - this creates an orphaned ACL.  In that case the identity reference is the SID of the original account.  

The current code simply took the identity reference and split it out at the \ to get the SAM account name.  Then the AD object could be pulled.

The new code now first checks to see if the identity reference is in the format of a SID S-1-5.   All windows object sids should be derivatives of S-1-5.  If the identity reference contains this - the ACL is logged and skipped.  Since the ACL was no longer valid - this is not a hard failure - just move on.

2.4.2 is now published with this code change - feel free to test and advise.

**Comment by timmcmic** [comment]
Closing
