### ISSUE TITLE
Error initializing default drive: when running Start-MultipleDistributionListMigration

### ISSUE THREAD

**Issue by YANSA23** [timmcmic/DLConversionV2#164]
I've been able to migrate single distribution lists(though with an emails address issue, separate), but when I try to migrate multiple at a time, I get: "WARNING: Error initializing default drive: 'Unable to find a default server with Active Directory Web Services running.'."

What I'm running:

```
$PSDefaultParameterValues['*-AD*:Server']` = 'ServerName.domain.suffix'

$Credentials = get-credential

$groups = get-content c:\POSH\DLs.txt
Start-MultipleDistributionListMigration -groupSMTPAddresses $groups -globalCatalogServer ServerName.domain.suffix -activeDirectoryAuthenticationMethod Kerberos -msGraphTenantID "XXXX" -msGraphCertificateThumbprint "XXXX" -msGraphApplicationID "XXXXX" -exchangeOnlineCertificateThumbPrint "XXXXXXXX" -exchangeOnlineOrganizationName "domain.suffix" -exchangeOnlineAppID "XXXXXXX" -logFolderPath C:\Temp -dnNoSyncOU “OU=DoNotSync,DC=domain,DC=edu” -aadConnectServer azureadc.olin.edu -aadConnectCredential $Credentials -aadConnectAuthenticationMethod Kerberos -exchangeServer exchangesever.domain.suffix -exchangeCredential $Credentials -exchangeAuthenticationMethod Kerberos

```

To clarify, I have to run "$PSDefaultParameterValues['*-AD*:Server']` = 'ServerName.domain.suffix'" due to my laptop being AAD joined and not on the local domain, but the Multiple Migration is the only time I've run into an issue so far with it not being recognized.

**Comment by timmcmic** [comment]
So this is probably because the multiple migration leverages jobs.  Being honest I've never had anyone do this.  So the multiple migration is going to spin up a controller, the controller is then going to provision one job for each machine.  I'm not sure what the machine being AAD Joined has to do with specifying the global catalog server as a part of the migration.

Tim

From: YANSA23 ***@***.***>
Sent: Thursday, April 11, 2024 9:27 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Error initializing default drive: when running Start-MultipleDistributionListMigration (Issue #164)


I've been able to migrate single distribution lists(though with an emails address issue, separate), but when I try to migrate multiple at a time, I get: "WARNING: Error initializing default drive: 'Unable to find a default server with Active Directory Web Services running.'."

What I'm running:

$PSDefaultParameterValues['*-AD*:Server']` = 'ServerName.domain.suffix'



$Credentials = get-credential



$groups = get-content c:\POSH\DLs.txt

Start-MultipleDistributionListMigration -groupSMTPAddresses $groups -globalCatalogServer ServerName.domain.suffix -activeDirectoryAuthenticationMethod Kerberos -msGraphTenantID "XXXX" -msGraphCertificateThumbprint "XXXX" -msGraphApplicationID "XXXXX" -exchangeOnlineCertificateThumbPrint "XXXXXXXX" -exchangeOnlineOrganizationName "domain.suffix" -exchangeOnlineAppID "XXXXXXX" -logFolderPath C:\Temp -dnNoSyncOU "OU=DoNotSync,DC=domain,DC=edu" -aadConnectServer azureadc.olin.edu -aadConnectCredential $Credentials -aadConnectAuthenticationMethod Kerberos -exchangeServer exchangesever.domain.suffix -exchangeCredential $Credentials -exchangeAuthenticationMethod Kerberos



To clarify, I have to run "$PSDefaultParameterValues['-AD:Server']` = 'ServerName.domain.suffix'" due to my laptop being AAD joined and not on the local domain, but the Multiple Migration is the only time I've run into an issue so far with it not being recognized.

-

**Comment by YANSA23** [comment]
So I would probably be better off by doing it in a foreach loop? Or one a server directly, but not ideal.. I suppose the foreach loop is fine for us being that we're pretty simple, so I'll leave it up to you if this can be closed

**Comment by timmcmic** [comment]
I would not recommend you do this in a for each loop.

Why does running the command and specifying the globalCatlogServer and credentials not work in your situation?

Tim

**Comment by YANSA23** [comment]
I'm not sure on the technical reason it doesn't work, I just know that it doesn't. Back when we spun up Intune and worked with an MSP, I put my device on AAD and early on we identified that trying to run anything against the local AD would result in the error about being unable to find a default server. 

I suspect this is due to my computer not being on the local domain that the DC is a part of, thus my machine can't naturally find it without me setting it in my PS session. When I stated implementing defining the default server, I've had no issues working with the local AD when creating accounts or running reports

**Comment by timmcmic** [comment]
Well yes - if you try to do any AD management command on a non-domain joined machine expecting discovery to work it will not work.

In this case though - I do not rely on any type of domain discovery but rather you specify the server, credentials, and credential type (Kerberos or basic).

Have you tried running the script as documented without this extra stuff?

Tim

**Comment by YANSA23** [comment]
Maybe I'm not following as I'm running it as documented. What is wrong with what is in the initial post here? 

The global catalog server is specified (redacted here), it prompts for credentials (which I use a domain admin account on), Kerberos is specified, etc.

**Comment by timmcmic** [comment]
Ok I was confused by the default parameter and missed the specified server in the command - sorry about that.

Can you send me an individual migration log -> dlconversionv2 at service dot Microsoft dot com.

Tim
