### ISSUE TITLE
session cleanup closes Powershell ISE

### ISSUE THREAD

**Issue by dimmthewitted** [timmcmic/DLConversionV2#26]
Start-DistributionListMigration cleanup closes my Powershell ISE window and have to repeatedly re-enter my onprem / cloudcred because re-opening is a new session.

**Comment by timmcmic** [comment]
Currently by design - exit is intentionally called upon any failure.  There's a pending item to try to adjust this while still preserving the ability to close multi-threaded migration jobs for the multi-threaded functions.

You may consider exporting your credentials to XML files to allow for easier importing as you test.

$onPremCred = get-credential
$cloudCred = get-credential

$onPremCred | export-cliXML -path c:\temp\onprem.xml
$cloudCred | export-cliXml -path c:\temp\cloud.xml

$onPremCred = import-cliXML -path c:\temp\onPremXML to use the credential.
