### ISSUE TITLE
globalCatalogServer requires Domain Controller

### ISSUE THREAD

**Issue by dimmthewitted** [timmcmic/DLConversionV2#28]
-globalCatalogServer argument looks like it requires a server running ADWS.  (a global catalog DC)

I am in a large corporate delegated environment where I am unable to run this against a DC unless we do a thorough code review / approval process.

Is there a way to run this without requiring a GlobalCatalog Server?

perhaps an option to change from the URI to a computername when creating the PS session?

Log:

Get-ADObject : Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.4.9.3\Get-ADObjectConfiguration.ps1:90 char:42
+ ... nfiguration=Get-ADObject -filter "mail -eq '$groupSMTPAddress'" -prop ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-ADObject], ADServerDownException
    + FullyQualifiedErrorId : ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Commands.GetADObject
 
Out-LogFile : Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.

**Comment by timmcmic** [comment]
No.  The entire premise of the script requires access to the domain controller.  It's how it does the group discovery, attribute discovery, scans the directory for dependencies etc.  You cannot eliminate it without using the script.  

The script uses standard ldap for most of the heavily lifting - and a remote powershell session for a handful of commands that must be resident to the domain controller.

If it helps you're organization is more than welcome to speak with me.  Otherwise this is probably a value proposition about the need to migrate DLs efficiently verses internal policy etc.

Thankfully the entire code based is published here online for their review!
