### ISSUE TITLE
Define variables?

### ISSUE THREAD

**Issue by derekhansell** [timmcmic/DLConversionV2#4]
Hey Tim!

Thanks so much for your work on this tool.

I just discovered v2 today when I was all set to run v1. I don't see a place to define variables like in v1 of the script - does the script prompt for that stuff when you run it?

Thanks!

**Comment by timmcmic** [comment]
http://timmcmic.wordpress.com see post #1 on how to start using this.

It's now a powershell module.

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: derekhansell ***@***.***>
Sent: Wednesday, August 11, 2021 11:01 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Define variables? (#4)


Hey Tim!

Thanks so much for your work on this tool.

I just discovered v2 today when I was all set to run v1. I don't see a place to define variables like in v1 of the script - does the script prompt for that stuff when you run it?

Thanks!

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimmcmic%2FDLConversionV2%2Fissues%2F4&data=04%7C01%7Ctimmcmic%40microsoft.com%7C9210633bdfaf4767a63908d95cd8e060%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637642908824720151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2sbJBt5Gdmdx7h%2Bo3ER3n%2FHvRzZORyAPUWUSmBz%2BDbc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKGTN6OH5D36Y2FOMFU2WC3T4KGD7ANCNFSM5B6XGOYA&data=04%7C01%7Ctimmcmic%40microsoft.com%7C9210633bdfaf4767a63908d95cd8e060%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637642908824720151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U6mEoMXVdqB6lCrKWecRPtjUFotA2FyX8K%2BPTqS%2FGNQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctimmcmic%40microsoft.com%7C9210633bdfaf4767a63908d95cd8e060%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637642908824730146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NlGomDS7drgpXDwdvpWuOeqxOtd5ioq2yf2bY6eR2rc%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ctimmcmic%40microsoft.com%7C9210633bdfaf4767a63908d95cd8e060%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637642908824730146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xaUwVJP%2BxRQJ5hnFfxsqxuVh6sp0q4K4iDdZ4xlsfZ8%3D&reserved=0>.

**Comment by derekhansell** [comment]
Here's the direct link to the post for anyone else looking for this:
https://timmcmic.wordpress.com/2021/04/25/4116/
