### ISSUE TITLE
Set-Office365DLMV Error

### ISSUE THREAD

**Issue by YouDontGitMe** [timmcmic/DLConversionV2#45]
Hi,

Thank you so much for your time and effort in making this script.  I'm getting an error below and I want to make sure I can bypass it without issues.

[3/25/2022 3:05:32 PM] - Uanble to set Office 365 DL Multi Value attributes - try again.
[3/25/2022 3:05:32 PM] - 5
[3/25/2022 3:05:38 PM] - END start-sleepProgess
[3/25/2022 3:05:38 PM] - ********************************************************************************
set-Office365DLMV : Cannot bind argument to parameter 'allOffice365SendAsAccessOnGroup' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.5.16\DLConversionV2.psm1:3865 char:790
+ ... oup -allOffice365SendAsAccessOnGroup $allOffice365SendAsAccessOnGroup
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [set-Office365DLMV], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,set-Office365DLMV

_______

If I edit the DLConversionV2.psm1 at line 3865 and set the alloffice365SendAsAccessOnGroup to $false - It does move past it, but I'm not sure I should go past it.  Nobody is sending as my groups, so it might be a non-issue.

**Comment by timmcmic** [comment]
Make sure you update - I believe o fixed this in yesterdays release.  Also make sure you’re getting the module from the powershell gallery,


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________
From: YouDontGitMe ***@***.***>
Sent: Friday, March 25, 2022 6:58 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Set-Office365DLMV Error (Issue #45)


Hi,

Thank you so much for your time and effort in making this script. I'm getting an error below and I want to make sure I can bypass it without issues.

[3/25/2022 3:05:32 PM] - Uanble to set Office 365 DL Multi Value attributes - try again.
[3/25/2022 3:05:32 PM] - 5
[3/25/2022 3:05:38 PM] - END start-sleepProgess
[3/25/2022 3:05:38 PM] - ********************************************************************************
set-Office365DLMV : Cannot bind argument to parameter 'allOffice365SendAsAccessOnGroup' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.5.16\DLConversionV2.psm1:3865 char:790

  *   ... oup -allOffice365SendAsAccessOnGroup $allOffice365SendAsAccessOnGroup
  *

                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


     *   CategoryInfo : InvalidData: (:) [set-Office365DLMV], ParameterBindingValidationException
     *   FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,set-Office365DLMV

________________________________

If I edit the DLConversionV2.psm1 at line 3865 and set the alloffice365SendAsAccessOnGroup to $false - It does move past it, but I'm not sure I should go past it. Nobody is sending as my groups, so it might be a non-issue.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimmcmic%2FDLConversionV2%2Fissues%2F45&data=04%7C01%7Ctimmcmic%40microsoft.com%7C5bc771427ef447e218a008da0eb2f376%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637838459003818595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S%2FCNFSkQmUt5HChMt55xLiBhcZ3mrLM%2FO8a8gVKKbzQ%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKGTN6NREFW5YCPJNO6Z4GDVBZAITANCNFSM5RVP5Y5Q&data=04%7C01%7Ctimmcmic%40microsoft.com%7C5bc771427ef447e218a008da0eb2f376%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637838459003818595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aiQCwSEh5KwRM4psipip9z8BnDDRvXKyoWy8q8FYt7g%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by timmcmic** [comment]
Hi!!!!  I found a regression in the build where I uploaded the wrong version.  .17 now has the fix in it.

This build introduced an additional array to track send as on the migrated DL.  There was a missed case where it tracked send as set directly on the DL on premises - but since this is a directory ACL it can also be set directly in the service.  The original module failed to account for this.

The missing code says that if the invocation finds no send as rights set directly in the cloud - set the array from NULL to @() [zero members].  In this case that was missing so when send as rights were not found - it resulted in trying to pass a NULL array.

Please update and advise - I reran the test suite and found no issues post code change.

**Comment by YouDontGitMe** [comment]
Thank you so much!  Updated the script and everything worked.  Thank you again, I was really dreading remaking so many DL's.
