### ISSUE TITLE
I get this issue when I run your module either on the Exchange server itself or a machine on the same subnet

### ISSUE THREAD

**Issue by Russtoleum** [timmcmic/DLConversionV2#46]
New-PSSession : [exchangeserver.company.org] Connecting to remote server exchangeserver.company.org failed with the following

error message : The WinRM client sent a request to an HTTP server and got a response saying the requested HTTP URL was

not available. This is usually returned by a HTTP server that does not support the WS-Management protocol. For more

information, see the about_Remote_Troubleshooting Help topic.

At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\New-PowershellSession.ps1:119 char:34

(Here is line 119: $sessiontoimport=New-PSSession -ConfigurationName $configurationName -ConnectionUri $connectionURI -Credential $credentials -AllowRedirection:$allowRedirection -Authentication $authenticationType -name $PowershellSessionName)

I have confirmed that WinRM is enabled and the ports are open on the firewall on the exchange server. I can open a pssession from the machine I am trying to run this on to the exchange server and I have even tried to run this module on the exchange server itself but I continue to get this error.

**Comment by timmcmic** [comment]
Have you followed the guidance to ensure that basic authentication is enabled on the powershell virtual directory?

Are you setting up the session by hand using basic auth and the same url?

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________
From: Russtoleum ***@***.***>
Sent: Wednesday, March 30, 2022 3:47 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] I get this issue when I run your module either on the Exchange server itself or a machine on the same subnet (Issue #46)


New-PSSession : [exchangeserver.company.org] Connecting to remote server exchangeserver.company.org failed with the following

error message : The WinRM client sent a request to an HTTP server and got a response saying the requested HTTP URL was

not available. This is usually returned by a HTTP server that does not support the WS-Management protocol. For more

information, see the about_Remote_Troubleshooting Help topic.

At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\New-PowershellSession.ps1:119 char:34

(Here is line 119: $sessiontoimport=New-PSSession -ConfigurationName $configurationName -ConnectionUri $connectionURI -Credential $credentials -AllowRedirection:$allowRedirection -Authentication $authenticationType -name $PowershellSessionName)

I have confirmed that WinRM is enabled and the ports are open on the firewall on the exchange server. I can open a pssession from the machine I am trying to run this on to the exchange server and I have even tried to run this module on the exchange server itself but I continue to get this error.

**Comment by tco-bfisk** [comment]
First off, I didn't use my local Exchange server. All user mailboxes were migrated off, exchange hybrid never configured, old connectors removed. It was only in place as a way for the help desk to modify groups via a GUI using Exchange Web Console on the old server (hence the project that led me down this road).  But I figured this would be a good time to share my "wrapper" scripts I made to use the module. Maybe it will help?

I've used the last few versions of Tim's module on different machines with my "wrapper" and it seems to be working for me. It's rudimentary and probably has some fluff that I took from my previous attempts at creating Powershell Scripts, which I now know how much of an amateur I am after seeing Tim's scripting!

I run from a member server in the domain where the source groups are located. My AADC server is in a different forest (across AD Trust). I first ran on a DC in the source domain, then another member server, and another. I use the following two scripts to do my multiple group migrations.

The first is **Prepare-Migration.ps1**.  This script installs and updates modules as well as sets connection variables. I have a section at the top where you can hard code variable defaults. You are then prompted for everything. The only thing I don't have built into the script is the generation and setup of the certificate with O365 for PS authentication but the instructions are in there commented out. 

I have a second script I use called **Perform-Migration.ps1**. This script actually performs the migration. It will search for the OU name specified, get all distribution groups from that OU, and then feed into Tim's migration module. This script also has a section for hard coding default values. If you've got lots of nested groups, you will have to rerun them multiple times to catch all the nested children.

To run, I'll open a new PowerShell window and run the first script with a dot space to keep the variables in session: `. .\Prepare-Migration.ps1`

I run the second script `.\Perform-Migration.ps1` so the variable values are not set in the current session. Otherwise, if you ran like the Prepare script and you moved onto another group or reran to catch nested groups that failed before, the existing values would be used.

Thank you Tim for this awesome module! I successfully finished a major part of my migration project with just under 800 distribution groups used across 15 countries.

[Prepare-Migration.ps1.txt](https://github.com/timmcmic/DLConversionV2/files/8383974/Prepare-Migration.ps1.txt)
[Perform-Migration.ps1.txt](https://github.com/timmcmic/DLConversionV2/files/8383973/Perform-Migration.ps1.txt)

**Comment by Russtoleum** [comment]
Timothy, thank you! Basic auth was indeed disabled for the powershell Virtual Directory. I think that was my final hurdle. Though I still am having errors, I am going to try and figure it out before I ask for more direction as I am sure you are quite busy.

**Comment by timmcmic** [comment]
Feel free to send the logs over and we can see where they're erroring.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by Russtoleum** [comment]
[4/4/2022 12:24:15 PM] - Attepmting to find the user via distinguished name.
[4/4/2022 12:24:15 PM] - Error getting AD object.  Sleep and try again.

[91mGet-ADObject: [91mVariable: 'dn' found in expression: $dn is not defined.
[0m

[91mOut-LogFile: [0mC:\Users\\Documents\PowerShell\Modules\DLConversionV2\2.5.16\Get-NormalizedDN.ps1:141
[96mLine |
[96m 141 | [0m                     [96mOut-LogFile -string $_ -isError:$TRUE[0m
[96m     | [91m                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mVariable: 'dn' found in expression: $dn is not defined.

Is that enough?

**Comment by timmcmic** [comment]
Nah I need to see what the entire call looks like.

***@***.******@***.***> you can zip and email the logs safely.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by timmcmic** [comment]
Dlconversionv2 at service dot microsoft dot com

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by Russtoleum** [comment]
Just emailed from my work email.
