### ISSUE TITLE
null-valued expression error with nested Groups

### ISSUE THREAD

**Issue by PeterNagl** [timmcmic/DLConversionV2#56]
Hi again, 

I am using version 2.0.5.
When I try to migrate a DL that is member of a different DL it stops with error:

```
[13.07.2022 14:32:43] - Gathering the AD object based on distinguished name.
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.5.22\Get-CanonicalName.ps1:100 char:13
+             $functionDomain=$functiontest.canonicalName.split("/")
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

This is pointing to an issue in Get-CanonicalName.ps1
LINE69
$functionTest = get-adobject -filter {distinguishedname -eq $dn} -properties canonicalName -credential $adCredential -errorAction STOP

When I try the same command from a new PowerShell session, I also get an error because get-adobject is searching in the Domain of the client I am running the script off and not the Domain where the Group is located.

Get-CanonicalName.ps1 receives a parameter for $globalCatalogServer but never us it.

I fixed the issue in my local version by pointing get-adobject to the GC
LINE69
`$functionTest = get-adobject -filter {distinguishedname -eq $dn} -properties canonicalName -credential $adCredential -Server $globalCatalogServer -errorAction STOP
`

Maybe you also want to test in LINE100 if $functionTest has a value.

kind regards
Peter

**Comment by timmcmic** [comment]
Please submit the full log to ***@***.******@***.***>

Dlconversionv2 at service dot microsoft dot com

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: Peter Nagl ***@***.***>
Sent: Wednesday, July 13, 2022 10:04 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] null-valued expression error with nested Groups (Issue #56)


Hi again,

I am using version 2.0.5.
When I try to migrate a DL that is member of a different DL it stops with error:

[13.07.2022 14:32:43] - Gathering the AD object based on distinguished name.

You cannot call a method on a null-valued expression.

At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.5.22\Get-CanonicalName.ps1:100 char:13

+             $functionDomain=$functiontest.canonicalName.split("/")

+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException

    + FullyQualifiedErrorId : InvokeMethodOnNull

This is pointing to an issue in Get-CanonicalName.ps1
LINE69
$functionTest = get-adobject -filter {distinguishedname -eq $dn} -properties canonicalName -credential $adCredential -errorAction STOP

When I try the same command from a new PowerShell session, I also get an error because get-adobject is searching in the Domain of the client I am running the script off and not the Domain where the Group is located.

Get-CanonicalName.ps1 receives a parameter for $globalCatalogServer but never us it.

I fixed the issue in my local version by pointing get-adobject to the GC
LINE69
$functionTest = get-adobject -filter {distinguishedname -eq $dn} -properties canonicalName -credential $adCredential -Server $globalCatalogServer -errorAction STOP

Maybe you also want to test in LINE100 if $functionTest has a value.

kind regards
Peter

-

**Comment by PeterNagl** [comment]
Hi Tim, after fixing the issue, I migrated all groups without a problem and deleted the FAILED logs.
Next week we will do another Batch of Groups and I can generate new Logs.
kind regards Peter

**Comment by timmcmic** [comment]
Peter

What did you fix?  That might help me isolate this some…

Tim


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________

**Comment by PeterNagl** [comment]
I fixed the issue in my local version by pointing get-adobject to the GC in Get-CanonicalName.ps1
LINE69
$functionTest = get-adobject -filter {distinguishedname -eq $dn} -properties canonicalName -credential $adCredential **-Server $globalCatalogServer** -errorAction STOP

Without specifying the GC the command tries to lookup the Group in the local Forest (which is not the Exchange Forest).
I will get you the logfiles for sure.

Peter

**Comment by timmcmic** [comment]
Peter:

So that I understand the scenario.

You're running the script from a machine that's in your account forest - but you're migrating a group that comes from a different exchange resource forest?

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by PeterNagl** [comment]
I run the migration on the AD Connect Server, which is member of one forest (A) out of 7 forests and all are Exchange Hybrid to the same Tenant. You are correct, the issue happens when I migrate a DL of a different forest (eg. B).
Server that runs the migration module = Forest A
AD Connect Server = Forest A
Exchange Server = Forest B
GC = Forest B 

I could, of course run the migration script in Forest B, but then I need to switch migration server all the time.
But since I put the GC into get-adobject, all works well.
The function "get-canonicalName" even has a parameter for the GC, but it is not used in the function (so far).


Function get-canonicalName
     {
        [cmdletbinding()]

        Param
        (
            [Parameter(Mandatory = $true)]
            [string]$globalCatalogServer,
            [Parameter(Mandatory = $true)]
            [string]$DN,
            [Parameter(Mandatory = $true)]
            $adCredential
        )


kind regards
Peter

**Comment by timmcmic** [comment]
Ok - there was someone else who pointed out an inefficiency here a few weeks ago.  I’m going to go ahead and revert a code change and change the code to a gc call on port.

I’ll let you know when the build is up to test.


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________

**Comment by PeterNagl** [comment]
Sounds great, thank you!

**Comment by timmcmic** [comment]
Peter:

If you download the following branch zip file.

timmcmic/DLConversionV2 at RefineADCalls (github.com)<https://github.com/timmcmic/DLConversionV2/tree/RefineADCalls>

Expand the zip file to a folder.

Navigate powershell to the folder.

Unblock-file *

Import-module dlconversionv2 -force

Then try - this has the updated GC with port reference in get-canonicalName.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by PeterNagl** [comment]
Hi Tim, just want to say that I still was not able to test the new build in production because I need to fix 2 other issues that came up in that project. By solving this 2 issues I found 2 other Issues in DLConversionV2 which I will post shortly.
