### ISSUE TITLE
Create HybridMailflow objects from Cloud only failes

### ISSUE THREAD

**Issue by PeterNagl** [timmcmic/DLConversionV2#58]
Hi, this one was tricky and maybe is a very special case.
I need to create the hybrid mailflow objects (dynamic DL and contact) in a forest that wasn´t the source of the DL that was migrated to EXO.
Maybe that is not a common use, but I think it is usefull if:

- Someone create a new DL in the Cloud and there are still onPrem Mailboxes that also need that DL in the GAL
- Someone removed the onprem objects (dynamic DL and contact) and we need to recreate them.

Lucky me found you function "enable-hybridMailFlowPostMigration"
But it has 2 issues if there is no onprem contact and needs to create the contact from the cloud DL.

There is a call to create the contact:              
new-routingContact -originalDLConfiguration $office365DLConfiguration -office365DlConfiguration $office365DLConfiguration -globalCatalogServer $globalCatalogServer -adCredential $activeDirectoryCredential -isRetry:$TRUE -isRetryOU $OU -errorAction STOP

$OriginalDLConfiguration is set to the office365DL (instead of the local AD DL)
isRetry is set to $True

Issue 1) in new-routingcontact
This is always executed:
[string]$functionOU=Get-OULocation -originalDLConfiguration $originalDLConfiguration

OriginalDL in that scenario is a O365 group and has the OU of that group is in the cloud and not found in the local AD.

FIX:
Test if isRetry is set and use the isRetryOU to point to the correct onprem OU to create the contact
`
      if ($isRetry) {
            [string]$functionOU=$isRetryOU
        } 
        else
        {
            [string]$functionOU=Get-OULocation -originalDLConfiguration $originalDLConfiguration
        }
`

Issue 2) in new-routingcontact
Script tries to extract the CN and mail attribute of the originalDLConfiguration, which normally is a onprem Object (with cn and mail), but in this case is a O365 DL without CN and without mail attribute

(possible) FIX:
Check if originalDLConfiguration is a O365 group object or onprem group object

     #Check if $originalDLConfiguration is a Cloud Object, when no local contact was found
        if ($originalDLConfiguration.PsObject.Properties.name -match "IsDirSynced") {
            out-logfile -string ("cloudDL found")

            #it is a cloud DL Configuration, we use .Identity for the CN of the new contact
            [string]$functionCN=$originalDLConfiguration.Identity+"-MigratedByScript"
            $functionCN=$functionCN.replace(' ','')
 
#it is a cloud DL Configuration, we use .WindowsEmailAddress instead of mail attribute [array]$functionProxyAddressArray=$originalDLConfiguration.WindowsEmailAddress.split("@")
        }
        else
        {
            #it is a OnPrem DL Configuration we use the CN and the mail attribute
            [string]$functionCN=$originalDLConfiguration.CN+"-MigratedByScript"
            $functionCN=$functionCN.replace(' ','')
            [array]$functionProxyAddressArray=$originalDLConfiguration.mail.split("@")        
        }

**Comment by timmcmic** [comment]
Phew ok - let me digest this one and get back to you.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: Peter Nagl ***@***.***>
Sent: Monday, July 25, 2022 5:15 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Create HybridMailflow objects from Cloud only failes (Issue #58)


Hi, this one was tricky and maybe is a very special case.
I need to create the hybrid mailflow objects (dynamic DL and contact) in a forest that wasn´t the source of the DL that was migrated to EXO.
Lucky me found you function "enable-hybridMailFlowPostMigration"
But it has 2 issues if there is no onprem contact and needs to create the contact from the cloud DL.

There is a call to create the contact:
new-routingContact -originalDLConfiguration $office365DLConfiguration -office365DlConfiguration $office365DLConfiguration -globalCatalogServer $globalCatalogServer -adCredential $activeDirectoryCredential -isRetry:$TRUE -isRetryOU $OU -errorAction STOP

$OriginalDLConfiguration is set to the office365DL (instead of the local AD DL)
isRetry is set to $True

Issue 1) in new-routingcontact
This is always executed:
[string]$functionOU=Get-OULocation -originalDLConfiguration $originalDLConfiguration

OriginalDL in that scenario is a O365 group and has the OU of that group is in the cloud and not found in the local AD.

FIX:
Test if isRetry is set and use the isRetryOU to point to the correct onprem OU to create the contact
if ($isRetry) { [string]$functionOU=$isRetryOU } else { [string]$functionOU=Get-OULocation -originalDLConfiguration $originalDLConfiguration }

Issue 2) in new-routingcontact
Script tries to extract the CN and mail attribute of the originalDLConfiguration, which normally is a onprem Object (with cn and mail), but in this case is a O365 DL without CN and without mail attribute

(possible) FIX:
Check if originalDLConfiguration is a O365 group object or onprem group object

` #Check if $originalDLConfiguration is a Cloud Object, when no local contact was found
if ($originalDLConfiguration.PsObject.Properties.name -match "IsDirSynced") {
out-logfile -string ("cloudDL found")

        #it is a cloud DL Configuration, we use .Identity for the CN of the new contact



        [string]$functionCN=$originalDLConfiguration.Identity+"-MigratedByScript"



        $functionCN=$functionCN.replace(' ','')



#it is a cloud DL Configuration, we use .WindowsEmailAddress instead of mail attribute [array]$functionProxyAddressArray=$originalDLConfiguration.WindowsEmailAddress.split("@")
}
else
{
#it is a OnPrem DL Configuration we use the CN and the mail attribute
[string]$functionCN=$originalDLConfiguration.CN+"-MigratedByScript"
$functionCN=$functionCN.replace(' ','')
[array]$functionProxyAddressArray=$originalDLConfiguration.mail.split("@")
}`

-

**Comment by PeterNagl** [comment]
Works perfect in your last build. Thank you!
